구구단 mvc 파일입니다
kebydays/campus-console-project pull request #6
Opened 2023-05-16 00:21 UTC by jeonjin616

2023-05-16 02:01 UTC, Keitiankor requested changes

2023-05-16 02:01 UTC, Keitiankor commented on Team9_Project1/GugudanView.java
> +    }
View 단에서는 컨트롤러에 접근할 필요가 없습니다

2023-05-16 02:01 UTC, Keitiankor commented on Team9_Project1/GugudanModel.java
> +        return sb.toString();
StringBuilder가 선언만 되고 사용되지 않았습니다.
for문 안에서 sysout이 아니라 StringBuilder.append() 함수를 사용하여 문자열을 만들어주고 반환해주면 될것같습니다.

2023-05-16 02:01 UTC, Keitiankor commented on Team9_Project1/GugudanView.java
> +            System.out.println("원하는 구구단의 단 수를 입력해 주세요.");
처음부터 입력 범위조건을 명시해주는것이 좋지 않을까요?🙄

2023-05-16 02:01 UTC, Keitiankor commented on Team9_Project1/GugudanController.java
> +        this.view = view;
생성자에서는 모델, 뷰를 각각 new해서 넣어주는것이 좋을것같습니다.

2023-05-16 05:41 UTC, jeonjin616 commented on Team9_Project1/GugudanModel.java
> +        return sb.toString();
잘 알겠습니다. StringBuilder 공부해서 적용해보도록 하겠습니다.👌

2023-05-16 05:42 UTC, jeonjin616 commented on Team9_Project1/GugudanView.java
> +            System.out.println("원하는 구구단의 단 수를 입력해 주세요.");
범위조건을 넣어 주는 것이 사용자에게 좀 더 직관적이겠네요. 반영토록 하겠습니다.

2023-05-16 05:54 UTC, jeonjin616 commented on Team9_Project1/GugudanController.java
> +        this.view = view;
this.model과 view 에서 new 를 쓰게되면 새로운 객체를 생성하게 되는 것 같은데, 저는 모델과 뷰에서 new 를 생략한 이유가 위에 private으로 보호받는 model과 view의 정보를 필드?에서 가져다 쓰기 위해 각각 this.로 매개변수로 지정해 주었습니다. 행여 제가 잘못 이해하고 있는 부분이 있다면 꼭 말씀해 주세요👍

2023-05-16 06:01 UTC, Keitiankor commented on Team9_Project1/GugudanController.java
> +        this.view = view;
컨트롤러 내에서 각각의 객체에 접근하기위해선 각 객체를 생성해주어야하고 그 역할은 생성자가 담당하는게 제일 무난합니다.
굳이 생성자에 생성된 인자를 넘겨주는경우 컨트롤러 내에서는 private로 접근이 제한되어있지만, 외부에서 생성된 객체를 통해 접근이 가능해질수 있기때문에 은닉화의 목적과 맞아 떨어지지 않는다고 생각합니다.

2023-05-16 06:07 UTC, jeonjin616 commented on Team9_Project1/GugudanView.java
> +    }
MVC 모델에서 룰 중에는 뷰는 컨트롤러를 통해 모델단과 연결되어야 하고 모델단과 뷰단에서는 서로 종속성이 없어야 한다고 알고 있습니다.! 🤔혹시나 잘못된 방법으로 호출은 한 것이라면 알려주세요!

2023-05-16 06:41 UTC, Keitiankor commented on Team9_Project1/GugudanController.java
> +        this.view = view;
@hyem808 이거 한번 봐보시면 좋겟습니다.
생성자에서 new해서 객체를 생성해주는게 생성자에 만들어진 객체를 넘겨주는것보다 은닉화에 유리합니다.

2023-05-17 04:04 UTC, Keitiankor commented on Team9_Project1/GugudanView.java
> +    }
뷰가 컨트롤러를 통해 모델단과 연결된다 라는뜻이 컨트롤러에서 뷰단과 모델단을 한번에 관리해준다는 의미입니다.
모델이나 뷰단에서 컨트롤러를 가지고 있게되면 모델과 뷰단이 서로 종속성을 가지게 될수 있습니다.

2023-05-17 12:17 UTC, hyem808 approved these changes
고생하셨습니다~

2023-05-18 04:00 UTC, Keitiankor approved these changes

2023-05-18 04:05 UTC, merged